<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class BaseModel extends Model
{
    //
    public function toArray()
    {
        $arr = parent::toArray(); // TODO: Change the autogenerated stub
        $keys = array_map(function ($key) {
            return lcfirst(Str::studly($key));
        }, array_keys($arr));
        $values = array_values($arr);
        return array_combine($keys, $values);
    }
}
